//
//  EateryData.swift
//  Eateries
//
//  Created by Kieran Murphy on 21/4/21.
//

import Foundation

let cottonCandy = Eatery(name: "Restaurant 1", desc: "A mixture of sugar and happiness", story: "My dentist hates me for eating this. Sorry, dentist.", recipe: ["Step 1 - Add sugar to the middle of the machine and twist the spinner to get the sugar evenly in the head.", "Step 2- Turn on the motor switch and turn on the heat switch.", "Step 3 - Catch the cotton candy with the cone as it comes out of the machine."], ingredients: ["4 cups of sugar", "1 cup of corn syrup", "1 cup of water", "4 ¼ teaspoon of salt", "1 tablespoon of raspberry extract", "2 drops of pink food colouring"], url: "https://www.visitbrisbane.com.au/~/media/articles/2020/november/elcaminocantina_20201125_wide.ashx")

let cupcake = Eatery(name: "Restaurant 2", desc: "A small yummy treat", story: "Icing is the most important part of a cupcake", recipe: ["Step 1 - Preheat oven to 180°C/160°C. Line muffin pans with paper cases.", "Step 2 - Using an electric mixer, beat butter, eggs, vanilla and sugar until light and fluffy. Transfer mixture to a large bowl. Stir in half the flour and milk. Repeat with remaining flour and milk until combined.", "Step 3 - For 1/3 cup-capacity muffin pans use 2 level tablespoons of mixture.", "Step 4 - Bake for 15 to 17 minutes.", "Step 5 - Transfer to a wire rack to cool."], ingredients: ["200g unsalted butter", "1 teaspoon vanilla extract", "1 cup caster sugar", "3 eggs", "2 ½ cups of self-raising flour", "½ cup of milk"], url: "https://www.hiddencitysecrets.com.au/wp-content/uploads/2018/08/Wilson-and-Market-restaurant-south-yarra-restaurants-melbourne-private-dining-fine-good-fancy-seafood-french-australian-modern-contemporary-best-top-005.jpg")

let donut = Eatery(name: "Restaurant 3", desc: "A delicious circular food", story: "Where did the hole go?", recipe: ["Step 1 – Combine flour, sugar, yeast and salt in a bowl. Make a well. Mix in milk, butter and egg until dough starts to come together.", "Step 2 - Knead on a well-floured surface until smooth. Place in a greased bowl. Cover. Prove for 1 1/2 hours or until dough has doubled in size.", "Step 3 - Punch down the dough. Knead on a lightly floured surface for 2 minutes or until smooth. Roll out dough until 1cm thick.", "Step 4 -  Use an 8cm round cutter to cut out discs. Use a 3.5cm round cutter to cut out centres. Place on a lined tray.", "Step 5 – Heat oil to 180°C. Deep-fry 4-5 doughnuts for 40 seconds each side or until puffed and golden."], ingredients: ["3 ¼  cups plain flour", "¼ cup caster sugar", "3 teaspoons dried yeast", "Pinch of salt", "1 cup of milk", "100g butter", "3 egg yolks", "Canola oil, to deep-fry", "1 cup of caster sugar"], url: "https://luxurysafes.me/blog/wp-content/uploads/2019/01/The-Top-10-Luxury-Restaurants-in-Paris-8.jpg")

let macaroon = Eatery(name: "Restaurant 4", desc: "A cute miniature cookie", story: "What's not to love about these?", recipe: ["Step 1 - In a food processor, combine sugar, flour, salt, and process on low speed, until extra fine.", "Step 2 - In a separate large bowl, beat the egg whites with an electric hand mixer until soft peaks form. Gradually add the sugar until fully incorporated. Continue to beat until stiff peaks form.", "Step 3 - Add vanilla, food colouring and ⅓ of the sifted almond flour mixture at a time to the beaten egg whites. Add the last additional almond flour and use a spatula to gently fold until combined.", "Step 4 - Transfer the macaron batter into a piping bag fitted with a round tip.", "Step 5 - Pipe the macarons onto the parchment paper in 1½-inch (3-cm) circles, spacing at least 1-inch (2-cm) apart.", "Step 6 - Let the macarons sit at room temperature for 30 minutes to 1 hour and preheat the oven to 300˚F (150˚C).", "Step 7 - Bake the macaroons for 17 minutes.", "Step 8 - Transfer the macaroons to a wire rack to cool completely before filling.", "Step 9 - To make the butter cream, combine butter, sugar, cream and vanilla and using a hand mixture beat to combine, until desired consistency is reached.", "Step 10 - Transfer the buttercream to a piping bag fitted with a round tip and pipe the macaroons."], ingredients: ["1 ¾ cups powdered sugar", "1 cup almond flour", "1 teaspoon salt", "3 egg whites", "¼ cup granulated sugar", "½ teaspoon vanilla extract", "2 drops pink food colouring", "1 cup unsalted butter"], url: "https://www.hiddencitysecrets.com.au/wp-content/uploads/2019/11/jellyfish-brisbane-restaurants-cbd-seafood-modern-restaurant-top-best-good-new-fine-dining-005-1.jpg")

let popsicle = Eatery(name: "Restaurant 5", desc: "Yummy ice cream on a stick", story: "Perfect in summer", recipe: ["Step 1 - Place the milk, vanilla, sugar, salt and cornflour in a saucepan. Whisk to combine.", "Step 2 While the mixture is heating, whisk the egg yolks in a bowl.", "Step 3 - Heat the milk-egg yolk mix on medium heat and bring it to a boil, while whisking regularly until you form a thick and pudding like custard.", "Step 4 - Cover and set aside to cool.", "Step 5 - When the custard has cooled, whisk the whipping cream until you get soft peaks.", "Step 6 - Keep the mixture in the fridge until you are ready to fill the popsicle moulds.", "Step 7 - Fill the moulds with the mixture, freeze and enjoy."], ingredients: ["1 cup of milk", "1 tablespoon of cornflour", "2 tablespoons of vanila bean paste", "½ cup of sugar", "3 egg yolks", "¼ tablespoons of salt", "1 cup of whipping cream"], url: "https://d4qwptktddc5f.cloudfront.net/03-XANVERI_BY_CESAR_ANCA_Restaurante_MAdrid_by_estudiHac_Jmferrero.jpg")

let rainbowCake = Eatery(name: "Restaurant 6", desc: "Taste the rainbow", story: "I love eating rainbow cake every time on my birthday", recipe: ["Step 1 - Combine buttermilk and the oil together and set aside.", "Step 2 - Combine the remaining buttermilk, egg whites, and vanilla together, whisk to break up the eggs and set aside.", "Step 3 - Combine flour, sugar, baking powder, and salt using a hand mixture.", "Step 4 - Add butter to the dry ingredients and mix on low until mixture resembles coarse sand.", "Step 5 - Add in your milk/oil mixture and let mix until dry ingredients are moistened.", "Step 6 - Add in your egg white/milk mixture in three batches, letting the batter mix for 15 seconds between additions.", "Step 7 - Divide your batter into 6 bowls and add different food colours to each batter.", "Step 8 - Bake your layers for 20-24 minutes at 168 Celsius or until the edges JUST start pulling away from the cake pan."], ingredients: ["680 g cake flour", "680 g granulated sugar", "1 tablespoon of salt", "2 tablespoons of baking power", "283 g of egg white", "170 g of vegetable oil", "510 g of buttermilk", "340 g of unsalted butter", "1 tablespoon of vanilla extract", "6 food colouring"], url: "https://cdn.thecoolist.com/wp-content/uploads/2010/09/larc-paris-restaurant-and-nightclub-6.jpg")

/// An array of all the favourite eateries
//var favouriteEateriesOriginal = [cottonCandy, cupcake, donut, macaroon, popsicle, rainbowCake]
